[[language]]
name = "python"

# In case you'd like to use ruff alongside black for code formatting:
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "elixir"
auto-format = true

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
# identifiers lower
formatter = { command = "sqlformat", args = ["--reindent", "--indent_width", "2","--identifiers", "lower", "--keywords", "upper", "-"] }
auto-format = true

[[language]]
name = "c"
auto-format = true

[language-server.clangd]
command = "clangd"
args = ["--function-arg-placeholders=0", "--query-driver=avr-gcc"]
# args = ["--query-driver=/usr/bin/avr-gcc"]
