[[language]]
name = "python"

# In case you'd like to use ruff alongside black for code formatting:
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "elixir"

auto-format = true
