[[language]]
name = "python"

# In case you'd like to use ruff alongside black for code formatting:
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "elixir"
auto-format = true
# scope = "source.elixir"
# file-types = ["ex", "exs"]
# diagnostic-severity = "Hint"
# comment-token = "#"
# indent = {tab-width = 2, unit = " "}
# injection-regex = "(elixir|ex)"
# shebangs = ["elixir"]
# roots = ["mix.exs", "mix.lock"]
# language-servers = [ "elixir-ls" ]


[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
