return {
  {
    'nvim-treesitter/nvim-treesitter',
    branch = 'main',
    lazy = false,
    config = function()
      require('nvim-treesitter').setup {}
      -- Ensure parsers are installed (no-op if already present).
      require('nvim-treesitter').install {
        'arduino',
        'c',
        'caddy',
        'cmake',
        'corn',
        'cpp',
        'css',
        'eex',
        'elixir',
        'erlang',
        'fish',
        'gitcommit',
        'git_config',
        'gitignore',
        'gleam',
        'go',
        'godot_resource',
        'heex',
        'html',
        'http',
        'javascript',
        'jinja',
        'jinja_inline',
        'json',
        'latex',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'markdown_inline',
        'python',
        'regex',
        'sql',
        'ssh_config',
        'typescript',
        'vue',
        'yaml',
      }
    end,
  },
}
