return {
  {
    'romus204/tree-sitter-manager.nvim',
    lazy = false,
    config = function()
      require('tree-sitter-manager').setup {
        ensure_installed = {
          'arduino',
          'c',
          'caddy',
          'cmake',
          'corn',
          'cpp',
          'css',
          'eex',
          'elixir',
          'erlang',
          'fish',
          'gitcommit',
          'git_config',
          'gitignore',
          'gleam',
          'go',
          'godot_resource',
          'heex',
          'html',
          'http',
          'javascript',
          'jinja',
          'jinja_inline',
          'json',
          'kitty',
          'latex',
          'lua',
          'luadoc',
          'make',
          'markdown',
          'markdown_inline',
          'python',
          'regex',
          'sql',
          'ssh_config',
          'typescript',
          'vue',
          'yaml',
        },
        auto_install = true,
        highlight = false,
      }
    end,
  },
}
